### ISSUE TITLE
LogicException

### ISSUE THREAD

**Issue by Gu3** [php-enqueue/enqueue-elastica-bundle#1]
Hi ! 
I tried to used the bundle, but I have an exception when I want to populate my Index : LogicException, No response in 180 seconds (the Resetting is ok) 

my config : 

```
enqueue:
    transport:
        default: 'fs'
        fs:
            store_dir: %kernel.root_dir%/logs/foselastica
```

Without the bundle, the populate works fine. 

I do something wrong ? 
Thanks !

Vincent.
